-- CreateTable
CREATE TABLE `Task` (
    `id` VARCHAR(191) NOT NULL,
    `name` ENUM('TRAFFIC_LINE_HAZARDS', 'BUILDINGS_HAZARDS', 'ELECTRONIC_SURVEILLANCE_REPORT', 'BUILDINGS_REPORT', 'BUSES_REPORT') NOT NULL,
    `frequency` ENUM('MONTHLY', 'INDIVIDUAL', 'DAILY', 'QUARTERLY') NOT NULL,
    `userId` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Task` ADD CONSTRAINT `Task_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
