import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from 'sonner'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: require('./favicon.jpg'),
};
import { IsOpenProvider } from '@/app/context/index'
import { LanguageProvider } from '@/app/context/LanguageContext'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <LanguageProvider>
          <IsOpenProvider>
            <Toaster
              dir="auto"
              richColors={true}
              position="top-center"
            />
            {children}
          </IsOpenProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
